---@type LangFile
return {
    misc = {
        text_disabled = "Disabled",
        text_minute = "minute",
        text_minute_plural = "minutes",
        text_player = "player",
        text_slot = "slot",
        text_slot_plural = "slots",
        text_star = "★",
        text_frame = "Frame",
        text_frame_plural = "Frames",
        text_diamond = "◆",
        text_quest_id = "[Quest ID: %s]",
    },
    menu = {
        config = {
            name = "Mod",
            enabled = "Enabled",
            reset = "Reset Settings",
        },
        language = {
            name = "Language",
            fallback = "Fallback",
            fallback_tooltip = "Display message in english if key is missing",
            font_size = {
                name = "Font Size",
                button_apply = "Apply",
            },
        },
        help = {
            name = "Help",
            unstuck_me = "Unstuck Me!",
            tooltip_unstuck_me = "If something goes wrong, this should close all the guis that block user input",
        },
        bind = {
            name = "Bind",
            tooltip_bound = "Already bound to",
            slider_buffer = "Buffer",
            tooltip_buffer = "Time window to detect multi-key combination (e.g. A+B) before triggering single keys",
            text_default = "Press any key...",
            button_add = "Add",
            button_save = "Save",
            button_remove = "Remove",
            button_cancel = "Cancel",
            button_clear = "Clear",
        },
    },
    mod = {
        category_ignore_attr = "Exclude Quest Attributes",
        category_ignore_monster = "Exclude Monsters",
        category_ignore_map = "Exclude Maps",
        category_require = "Require",
        category_weapon = "Exclude Weapons",
        category_auto = "Auto",
        button_ignore = "Exclude",
        button_ignore_all = "Exclude All",
        button_clear = "Clear",
        box_ignore_passcode = "Passcode",
        box_ignore_manualaccept = "Manual Accept",
        box_ignore_weapon_sub = "Check Secondary Weapons",
        combo_ignore_monster_state = {
            NONE = "Normal",
            NORMAL = "Tempered",
            KING = "Arch-Tempered",
            FRENZY = "Frenzied",
        },
        combo_ignore_monster_target = {
            SMALL = "Small Target",
            SINGLE = "Single Target",
            MULTI = "Multi Target",
        },
        combo_ignore_environ = {
            RUIN = "Ruin",
            ABNORMAL = "Abnormal",
            FERTILITY = "Fertility",
        },
        radio_start_quest = {
            PICK = "Pick Quest",
            START_AND_DEPART = "Accept Quest & Depart",
            START_AND_PREP = "Accept Quest & Prep",
            DISABLED = "Disabled",
        },
        radio_search_quest = {
            SEARCH = "Search Quest",
            DISABLED = "Disabled",
        },
        combo_ignore_multiplay_setting = {
            PLAYER_WITH_NPC = "Players & Support Hunters",
            PLAYER_ONLY = "Only Players",
            NPC_ONLY = "Only Support Hunters",
        },
        combo_ignore_quest_target = {
            EM_BOSS_HUNTING = "Hunt",
            EM_BOSS_KILL = "Kill",
            EM_BOSS_CAPTURE = "Capture",
            ITEM = "Gathering",
            EM_BOSS_REMAIN_HP = "Repel",
        },
        combo_weapon = {
            MELEE = "Melee",
            RANGED = "Ranged",
        },
        box_require_item_wishlist = "Wishlisted Item",
        box_require_item_rare = "Rare Item",
        box_require_boost = "Gathering Boost",
        slider_text_time = "Started longer than %s %s ago",
        slider_text_time_limit = "With time limit shorter than %s %s",
        slider_text_host_hr = "With host hunter rank below %s or above %s",
        combo_ignore_player_text = "%s %s %s remaining",
        combo_ignore_player_max_text = "%s max %s %s",
        box_auto_pick_quest = "Pick Quest",
        box_auto_start_quest = "Accept Quest",
        box_auto_search = "Search",
        tooltip_auto_search = "Start searching immediately after returning from a quest, requires Auto Accept or Auto Pick to be enabled",
        tooltip_item_rare = "'Shiny' items, plates, gems, etc.",
        tooltip_auto_start_quest = "Auto Accept requires Manual Accept, and Passcode filters to be enabled",
        tooltip_investigations_only = "Investigations Only",
        tooltip_item_wishlist = "Bonus Rewards contain wishlisted item",
        tooltip_item_wishlist_any = "Any monster that can drop a wishlisted item (incl. guaranteed quest rewards & Investigation Bonus Rewards)",
        tooltip_weapon_host = "Quest host",
        tooltip_weapon_member = "All quest members",
        tooltip_weapon_more = "Duplicate weapons",
        tooltip_weapon_sub = "Note: For duplicate weapons filter, each weapon and weapon category is counted once per player\n\nExamples:\nLong Sword/Long Sword → Long Sword = 1, Melee = 1\nLong Sword/Great Sword → Long Sword = 1, Great Sword = 1, Melee = 1\nLong Sword/Bow → Long Sword = 1, Bow = 1, Melee = 1, Ranged = 1",
        actions = {
            search_start = "Start Search",
            search_cancel = "Cancel Search",
        },
        input_quest_id = "Quest ID",
    },
}
