---@type LangFile
return {
    misc = {
        text_disabled = "Disabled",
        text_minute = "minute",
        text_minute_plural = "minutes",
        text_player = "player",
        text_slot = "slot",
        text_slot_plural = "slots",
        text_star = "★",
        text_frame = "Frame",
        text_frame_plural = "Frames",
        text_diamond = "♦",
    },
    menu = {
        config = {
            name = "Mod",
            enabled = "Enabled",
        },
        language = {
            name = "Language",
            fallback = "Fallback",
            fallback_tooltip = "Display message in english if key is missing",
        },
        help = {
            name = "Help",
            unstuck_me = "Unstuck Me!",
            tooltip_unstuck_me = "If something goes wrong, this should close all the guis that block user input",
        },
        bind = {
            name = "Bind",
            tooltip_bound = "Already bound to",
            slider_buffer = "Buffer",
            tooltip_buffer = "Time window to detect multi-key combination (e.g. A+B) before triggering single keys",
            text_default = "Press any key...",
            button_add = "Add",
            button_save = "Save",
            button_remove = "Remove",
            button_cancel = "Cancel",
            button_clear = "Clear",
        },
    },
    mod = {
        category_ignore_attr = "Exclude Quest Attributes",
        category_ignore_monster = "Exclude Monsters",
        category_ignore_map = "Exclude Maps",
        category_require = "Require",
        category_auto = "Auto",
        button_ignore = "Exclude",
        button_remove = "Remove",
        box_ignore_passcode = "Passcode",
        box_ignore_manualaccept = "Manual Accept",
        combo_ignore_monster_state = {
            NONE = "Normal",
            NORMAL = "Tempered",
            KING = "Arch-Tempered",
            FRENZY = "Frenzied",
        },
        combo_ignore_monster_target = {
            SMALL = "Small Target",
            SINGLE = "Single Target",
            MULTI = "Multi Target",
        },
        combo_ignore_environ = {
            RUIN = "Ruin",
            ABNORMAL = "Abnormal",
            FERTILITY = "Fertility",
        },
        combo_quest_start = {
            START_AND_DEPART = "Accept & Depart",
            START_AND_PREP = "Accept & Prep",
        },
        combo_ignore_multiplay_setting = {
            PLAYER_WITH_NPC = "Players & Support Hunters",
            PLAYER_ONLY = "Only Players",
            NPC_ONLY = "Only Support Hunters",
        },
        box_require_item_wishlist = "Wishlisted Item",
        box_require_item_rare = "Rare Item",
        box_require_boost = "Gathering Boost",
        slider_text_time = "Started longer than %s %s ago",
        slider_text_time_limit = "With time limit shorter than %s %s",
        slider_text_player = "With fewer than %s %s %s remaining",
        slider_text_player_max = "With fewer than %s max %s %s available",
        slider_text_rank_lower = "Easier than %s%s",
        slider_text_rank_upper = "Harder than %s%s",
        slider_text_host_hr_lower = "With host hunter rank below %s",
        slider_text_host_hr_upper = "With host hunter rank above %s",
        slider_text_monster_grade_lower = "Below %s%s",
        slider_text_monster_grade_upper = "Above %s%s",
        box_auto_pick_quest = "Pick Quest",
        box_auto_start_quest = "Accept Quest",
        box_auto_search = "Search",
        tooltip_auto_search = "Start searching immediately after returning from a quest",
        tooltip_item_rare = "'Shiny' items, plates, gems, etc.",
        tooltip_auto_start_quest = "Requires Manual Accept, and Passcode filters to be enabled",
        tooltip_investigations_only = "Investigations Only",
        tooltip_item_wishlist = "Bonus Rewards contain wishlisted item",
        tooltip_item_wishlist_any = "Any monster that can drop a wishlisted item (incl. guaranteed quest rewards & Investigation Bonus Rewards)",
        actions = {
            search_start = "Start Search",
            search_cancel = "Cancel Search",
        },
    },
}
